export const PRODUCTS = {
  restart: {
    badge: 'Blessure & reprise',
    name: 'TrainToRestart',
    desc: "Accompagnement mensuel pour reprendre la course avec un cadre clair, une progression cohérente et un suivi direct.",
    priceNum: '199',
    period: '/ mois',
    total: "199€ aujourd'hui puis 199€ / mois",
    buttonLabel: 'Payer 199€ / mois',
    features: [
      'Appel diagnostic 45 min en visio',
      'Plan de reprise personnalisé et évolutif',
      'Suivi hebdomadaire par message',
      'Appel mensuel de bilan (45 min)',
      'Accès direct à Thomas — pas une équipe',
    ],
    parent: { label: 'Coaching', href: '/coaching' },
    notice: 'Sans engagement · Résiliable à tout moment · Confirmation par email',
  },
  'perform-autonome': {
    badge: 'Performance autonome',
    name: 'TrainToPerform Autonome',
    desc: "Plan structuré sur quatre semaines, adapté à ton profil, pour t'entraîner seul avec un cadre fiable.",
    priceNum: '89',
    period: '/ mois',
    total: "89€ aujourd'hui puis 89€ / mois",
    buttonLabel: 'Payer 89€ / mois',
    features: [
      'Plan sur 4 semaines',
      'Volume et intensités adaptés à ton profil',
      "Objectif principal défini ensemble",
      "Repères d'allure et RPE",
      'Sans suivi coach direct',
    ],
    parent: { label: 'Coaching', href: '/coaching' },
    notice: 'Sans engagement · Résiliable à tout moment · Confirmation par email',
  },
  'perform-coaching': {
    badge: 'Performance accompagnée',
    name: 'TrainToPerform Coaching',
    desc: "Coaching course à pied avec plan évolutif, ajustements et contact direct pour progresser sans bricoler.",
    priceNum: '199',
    period: '/ mois',
    total: "199€ aujourd'hui puis 199€ / mois",
    buttonLabel: 'Payer 199€ / mois',
    features: [
      'Planification évolutive sur mesure',
      'Feedbacks réguliers sur tes séances',
      'Ajustements selon tes semaines réelles',
      'Contact direct coach',
      'Logique expliquée à chaque étape',
    ],
    parent: { label: 'Coaching', href: '/coaching' },
    notice: 'Sans engagement · Résiliable à tout moment · Confirmation par email',
  },
  consulting: {
    badge: 'Consulting',
    name: 'Bilan individualisé',
    desc: "Un bilan d'une heure pour lire ton contexte global, clarifier les priorités et prendre de meilleures décisions.",
    priceNum: '97',
    period: 'paiement unique',
    total: "97€ aujourd'hui — paiement unique",
    buttonLabel: 'Payer 97€',
    features: [
      "1 heure d'échange en visio",
      'Analyse globale de ton contexte',
      'Lecture entraînement et douleurs',
      'Axes prioritaires identifiés',
      'Recommandations de suite personnalisées',
    ],
    parent: { label: 'Consulting', href: '/consulting' },
    notice: 'Paiement unique · Lien de rendez-vous envoyé par email après confirmation',
  },
} as const

export type ProductKey = keyof typeof PRODUCTS
export type Product = (typeof PRODUCTS)[ProductKey]
