export const PRODUCTS = {
  restart: {
    badge: 'Blessure & reprise',
    name: 'TrainToRestart',
    desc: "Accompagnement mensuel pour reprendre la course avec un cadre clair, une progression cohérente et un suivi direct.",
    priceNum: '199',
    period: '/ mois',
    total: "199€ aujourd'hui puis 199€ / mois",
    buttonLabel: 'Payer 199€ / mois',
    features: [
      'Appel diagnostic 45 min en visio',
      'Plan de reprise personnalisé et évolutif',
      'Suivi hebdomadaire par message',
      'Appel mensuel de bilan (45 min)',
      'Accès direct à Thomas, pas une équipe',
    ],
    parent: { label: 'Coaching', href: '/coaching' },
    confirmationPath: '/confirmrestart',
    notice: 'Sans engagement · Résiliable à tout moment · Confirmation par email',
    plans: [
      {
        id: 'monthly',
        mode: 'subscription',
        stripePriceEnv: 'STRIPE_PRICE_RESTART_MONTHLY',
        label: 'Mensuel',
        detail: 'Résiliable à tout moment',
        price: '199€',
        period: '/ mois',
        total: "199€ aujourd'hui puis 199€ / mois",
        buttonLabel: 'Payer 199€ / mois',
      },
    ],
  },
  'perform-autonome': {
    badge: 'Performance autonome',
    name: 'TrainToPerform Autonome',
    desc: "Plan structuré sur quatre semaines, adapté à ton profil, pour t'entraîner seul avec un cadre fiable.",
    priceNum: '89',
    period: '/ mois',
    total: "89€ aujourd'hui puis 89€ / mois",
    buttonLabel: 'Payer 89€ / mois',
    features: [
      'Plan sur 4 semaines',
      'Volume et intensités adaptés à ton profil',
      "Objectif principal défini ensemble",
      "Repères d'allure et RPE",
      'Sans suivi coach direct',
    ],
    parent: { label: 'Coaching', href: '/coaching' },
    confirmationPath: '/confirmauto',
    notice: 'Sans engagement · Résiliable à tout moment · Confirmation par email',
    plans: [
      {
        id: 'monthly',
        mode: 'subscription',
        stripePriceEnv: 'STRIPE_PRICE_PERFORM_AUTONOME_MONTHLY',
        label: 'Mensuel',
        detail: 'Résiliable à tout moment',
        price: '89€',
        period: '/ mois',
        total: "89€ aujourd'hui puis 89€ / mois",
        buttonLabel: 'Payer 89€ / mois',
      },
      {
        id: 'six-months',
        mode: 'payment',
        stripePriceEnv: 'STRIPE_PRICE_PERFORM_AUTONOME_6_MONTHS',
        label: '6 mois',
        badge: '-11%',
        detail: 'Paiement unique · sans reconduction',
        price: '474€',
        period: 'paiement unique',
        total: "474€ aujourd'hui, 6 mois inclus",
        buttonLabel: 'Payer 474€',
      },
      {
        id: 'twelve-months',
        mode: 'payment',
        stripePriceEnv: 'STRIPE_PRICE_PERFORM_AUTONOME_12_MONTHS',
        label: '12 mois',
        badge: '-22%',
        detail: 'Paiement unique · sans reconduction',
        price: '828€',
        period: 'paiement unique',
        total: "828€ aujourd'hui, 12 mois inclus",
        buttonLabel: 'Payer 828€',
      },
    ],
  },
  'perform-coaching': {
    badge: 'Performance accompagnée',
    name: 'TrainToPerform Coaching',
    desc: "Coaching course à pied avec plan évolutif, ajustements et contact direct pour progresser sans bricoler.",
    priceNum: '199',
    period: '/ mois',
    total: "199€ aujourd'hui puis 199€ / mois",
    buttonLabel: 'Payer 199€ / mois',
    features: [
      'Planification évolutive sur mesure',
      'Feedbacks réguliers sur tes séances',
      'Ajustements selon tes semaines réelles',
      'Contact direct coach',
      'Logique expliquée à chaque étape',
    ],
    parent: { label: 'Coaching', href: '/coaching' },
    confirmationPath: '/confirmcoaching',
    notice: 'Sans engagement · Résiliable à tout moment · Confirmation par email',
    plans: [
      {
        id: 'monthly',
        mode: 'subscription',
        stripePriceEnv: 'STRIPE_PRICE_PERFORM_COACHING_MONTHLY',
        label: 'Mensuel',
        detail: 'Résiliable à tout moment',
        price: '199€',
        period: '/ mois',
        total: "199€ aujourd'hui puis 199€ / mois",
        buttonLabel: 'Payer 199€ / mois',
      },
      {
        id: 'six-months',
        mode: 'payment',
        stripePriceEnv: 'STRIPE_PRICE_PERFORM_COACHING_6_MONTHS',
        label: '6 mois',
        badge: '-12%',
        detail: 'Paiement unique · sans reconduction',
        price: '1 050€',
        period: 'paiement unique',
        total: "1 050€ aujourd'hui, 6 mois inclus",
        buttonLabel: 'Payer 1 050€',
      },
      {
        id: 'twelve-months',
        mode: 'payment',
        stripePriceEnv: 'STRIPE_PRICE_PERFORM_COACHING_12_MONTHS',
        label: '12 mois',
        badge: '-25%',
        detail: 'Paiement unique · sans reconduction',
        price: '1 800€',
        period: 'paiement unique',
        total: "1 800€ aujourd'hui, 12 mois inclus",
        buttonLabel: 'Payer 1 800€',
      },
    ],
  },
} as const

export type ProductKey = keyof typeof PRODUCTS
export type Product = (typeof PRODUCTS)[ProductKey]
